name: SimpleSpawn
main: me.ellbristow.SimpleSpawn.SimpleSpawn
version: 2.0.4
database: true
author: ellbristow
dev-url: http://dev.bukkit.org/server-mods/simplespawn
description: >
             Set the world's spawn location
commands:
  setspawn:
    description: Set spawn location
  spawn:
    description: Teleport to spawn location
  home:
    description: Teleport to home location
  setjail:
    description: Set jail location
  jail:
    description: Jail a player
  jails:
    description: Show list of Jails
  release:
    description: Release a player from jail
permissions:
  simplespawn.*:
    description: Access to all SimpleSpawn commands
    children:
      simplespawn.set: true
      simplespawn.use: true
      simplespawn.use.worlds: true
      simplespawn.home: true
      simplespawn.jail.*: true
  simplespawn.home:
    description: Access to /home
  simplespawn.jail.*:
    description: Access to /jail and /setjail
    children:
      simplespawn.jail.set: true
      simplespawn.jail.use: true
      simplespawn.jail.release: true
      simplespawn.jail.immune: true
      simplespawn.jail.list: true
  simplespawn.use.default:
    description: Access to /spawn for SSdefault location
  simplespawn.set:
    description: Access to /setspawn
  simplespawn.use:
    description: Access to /spawn
  simplespawn.use.worlds:
    description: Access to /spawn {worldName}
  simplespawn.home:
    description: Access to /home
  simplespawn.jail.use:
    description: Access to /jail
  simplespawn.jail.release:
    description: Access to /release
  simplespawn.jail.set:
    description: Access to /setjail
  simplespawn.jail.list:
    description: Access to /jails
  simplespawn.jail.immune:
    description: Player can't be jailed
